Week4 report
1. Correlation between S4AQ6A and S4CQ5 (numeric variable case)
In the first section, two numeric variables are studied. S4CQ5: the age at the onset of minor depression. S4AQ6A: the age at the onset of major depression. Intuitively, these two variables can be highly correlated, because people who have minor depression could sooner or later become a major depression, and peole who had major depression could have minor depression following up with it.

The frequency distribution of S4CQ5 is

 hist(nesar_pds$S4CQ5);
In the command line run:

hist(nesar_pds$S4CQ5);


This plot shows that, most peole tend to develop minor depression problem during age 10 to 60.

The frequency distribution of S4AQ6A is

 hist(nesar_pds$S4AQ6A);
In the command line run:

 hist(nesar_pds$S4AQ6A);


And this frequency distribution shows the same trend as that of the S4CQ5, which indicates their correlations. To visualize the correlations, a data frame called major_vs_mino is created, and ggplot2 is used to visualize the data as below:

major_vs_mino <- data.frame(S4AQ6A = nesar_pds$S4AQ6A, S4CQ5 = nesar_pds$S4CQ5); 
g1<-ggplot(major_vs_mino, aes(x=S4CQ5, y=S4AQ6A))+ geom_point() + labs(title='Age at onset of minor vs major depression')
In the command line run:

g1;
## Warning in loop_apply(n, do.ply): Removed 41269 rows containing missing
## values (geom_point).


From the visualized plot, it is clear to see that the linear-like correlation between age of onset of minor depression and major depression. And it is confirmed that peole who had minor depression is likely to have major depression in that age. Minor depression is likely to cause major depression in that age, and people who experienced major depression is likely to have minor depression to follow up.

2. Correlation between S4AQ1 and S4AQ2 (factor variable case).
The previous section studies the correlation between two numeric variables, this section study the correlation between two factor variables.

Intuitively, there should be correlation between S4AQ1 and S4AQ2. S4AQ1: Ever had 2 week period when felt sad, blue, depressed or down most of time. S4AQ2: Ever had 2 week period when didn’t care about things usrally cared about.

Since both varibles has only values 1, 2 and NA, it is considered to be factor variables, thus it is not reasonable to visualize. Hence, use pearson correlation to study the correlation between these two variables.

cor.test(nesar_pds[,'S4AQ1'], nesar_pds[,'S4AQ2']);
The correlation test result shows the following:

        Pearson's product-moment correlation

data:  nesar_pds[, "S4AQ1"] and nesar_pds[, "S4AQ2"]
t = 240.75, df = 42121, p-value < 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.7569662 0.7650047
sample estimates:
      cor 
0.7610147 
In which, the correlation is between these two data is as high as 76.1%. The confidence interval is very narrow, and the p value is very small. This indicates that the estimated correlation of 76.1% is a significant one, and if the data is uncorrelated, it is very unlikely to achieve is number. By using the hypothesis test, it is fair to reject the null hypothesis that assumes cor = 0, and adapt the alternative hypothesis believing that cor = 76.1%.
